version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: nginx
    env_file:
      - ./.env
    ports:
      - $NGINX_EXTERNAL_PORT:$NGINX_INTERNAL_PORT
    networks:
      - nodenetwork
    depends_on:
      - app
  db:
    container_name: db
    build:
      context: mysql
    env_file:
      - ./.env
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql/database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    networks:
      - nodenetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 2
  app:
    container_name: app
    build:
      context: node
    entrypoint: node src/index.js
    tty: true
    networks:
      - nodenetwork
    depends_on:
      db:
        condition: service_healthy
networks:
  nodenetwork:
    driver: bridge