version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: nginx
    env_file:
      - ./.env
    ports:
      - $NGINX_EXTERNAL_PORT:$NGINX_INTERNAL_PORT
    networks:
      - nodenetwork
    depends_on:
      - app
  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    env_file:
      - ./.env
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql/database:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    networks:
      - nodenetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
  app:
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    build:
      context: node
    command: bash -c "npm i -y && node src/index.js"
    tty: true
    networks:
      - nodenetwork
    depends_on:
      db:
        condition: service_healthy
networks:
  nodenetwork:
    driver: bridge