version: '3'

services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - nodenetwork
    ports:
      - "8080:80"
    depends_on:
      - app
  db:
    build:
      context: mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenetwork
  app:
    build:
      context: node
    networks:
      - nodenetwork
    entrypoint: wait-for db:3306 -t 40 -- node src/index.js
    tty: true
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db
networks:
  nodenetwork:
    driver: bridge